table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		iif "lo" accept
		ct state established,related accept
		ip saddr 192.168.50.0/24 tcp dport 22 accept
		ip6 saddr fe80::/64 tcp dport 22 accept
		ip protocol icmp accept
		ip6 nexthdr ipv6-icmp accept
	}
}
